base_url = "https://academic-university.github.io/dnd/"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]
default_language = "ru"

[markdown.highlighting]
theme = "catppuccin-mocha"

[[taxonomies]]
name = "tags"
feed = true

[[taxonomies]]
name = "time"
feed = true
